name: Enforcing Coding Styles

on:
  push:
    branches: [feat-project-setup, dev]
  pull_request:
    branches: [feat-project-setup, dev, staging]

jobs:
  lint-and-format:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      # Run ESLint
      - name: Run lint
        run: npm run lint

      # Run Prettier
      - name: Run format check
        run: npm run format -- --check
